# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabiduria', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=100)),
                ('in_team', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=15)),
                ('asked', models.CharField(max_length=100)),
                ('date_ask', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bot_user_id', models.CharField(max_length=20)),
                ('bot_access_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('in_team', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=300)),
            ],
        ),
    ]
